[package]
name = "runcat-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.5", default-features = false, features = ["rayon", "ico"] }
sysinfo = { version = "0.33.1", default-features = false, features = ["multithread", "system"] }
tao = "0.31.1"
tray-icon = "0.19.2"
